// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zybdhttbttyoitqdsuoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YmRodHRidHR5b2l0cWRzdW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTc0MjgsImV4cCI6MjA2ODI3MzQyOH0.gl0ORqej00yNHHeShpMHicXLcMT8iPWSUCEvpK6V31E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});